#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/WheeStat6_0d.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/gicentreUtils.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" WheeStat6_0d "$@"
